build(deps): Bump cosmwasm-std from 1.4.0 to 1.4.1 (#350)
Bumps [cosmwasm-std](https://github.com/CosmWasm/cosmwasm) from 1.4.0 to 1.4.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/CosmWasm/cosmwasm/releases">cosmwasm-std's releases</a>.</em></p>
<blockquote>
<h2>v1.4.1</h2>
<p>Attached there are some build artifacts generated at this tag. Those are for development purposes only! Please use crates.io to find the packages of this release.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/CosmWasm/cosmwasm/blob/v1.4.1/CHANGELOG.md">cosmwasm-std's changelog</a>.</em></p>
<blockquote>
<h2>[1.4.1] - 2023-10-09</h2>
<h2>Fixed</h2>
<ul>
<li>cosmwasm-vm: Fix a 1.3.x -&gt; 1.4.0 regression bug leading to a <em>Wasmer runtime
error: RuntimeError: out of bounds memory access</em> in cases when the Wasm file
is re-compiled and used right away. (<a href="https://redirect.github.com/CosmWasm/cosmwasm/issues/1907">#1907</a>)</li>
</ul>
<p><a href="https://redirect.github.com/CosmWasm/cosmwasm/issues/1907">#1907</a>: <a href="https://redirect.github.com/CosmWasm/cosmwasm/pull/1907">CosmWasm/cosmwasm#1907</a></p>
<h3>Changed</h3>
<ul>
<li>cosmwasm-check: Use &quot;=&quot; for pinning the versions of cosmwasm-vm and
cosmwasm-std dependencies. This ensures that you can use an older version of
cosmwasm-check together with the VM of the same version by doing
<code>cargo install cosmwasm-check@1.4.1</code>. A typical use case would be to check a
contract with CosmWasm 1.4, 1.5 and 2.0. Note that other dependencies are
still upgraded when using <code>cargo install</code> which may lead to API, behavioural
or compiler incompatibilities. The
<a href="https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile">--locked</a>
feature allows you use the versions locked when the release was created.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/9410fa2f76e576d3eaa2a0a53036d4a97e2705fe"><code>9410fa2</code></a> Fix docs.rs features</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/dc2eca73c53d5ab27c85910f109fd790ee2527fe"><code>dc2eca7</code></a> Set version: 1.4.1</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/e99425bdbd7f00b856e4841888ded7937f8056f0"><code>e99425b</code></a> Fix bug for the pin implementation</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/b76c1e5bcb578da5359caa11b0cf114e0d086aca"><code>b76c1e5</code></a> Annotate compiled module consistenly</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/7c7b93d9c6a401ed36742d9f3da2e03f5adebc75"><code>7c7b93d</code></a> Reproduce bug in pin implementation</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/85201719fb61776389cd2b47fc59e6bfce819025"><code>8520171</code></a> Execute instances in pin_unpin_works test</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/949d82b267b220d9e9626f52a78aef359488c98d"><code>949d82b</code></a> Pull out test_hackatom_instance_execution</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/d9e05924d660a4914c29e707299865603563e7d2"><code>d9e0592</code></a> Fix misuse of Module</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/a440660a9b915bdf56d729afa2f58cfc3177bfaa"><code>a440660</code></a> Add test reproducing the issue</li>
<li><a href="https://github.com/CosmWasm/cosmwasm/commit/3579e839e6e0c9cee6fa9119dbbd38ed5ea4d1bc"><code>3579e83</code></a> Fix test comments init -&gt; instantiate</li>
<li>Additional commits viewable in <a href="https://github.com/CosmWasm/cosmwasm/compare/v1.4.0...v1.4.1">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=cosmwasm-std&package-manager=cargo&previous-version=1.4.0&new-version=1.4.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>